dist: xenial

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/601eba4ae3738ceb2406
    on_success: change
    on_failure: always
    on_start: never

addons:
  apt:
    update: true

install:
  - pip install --upgrade "pip<20.0" setuptools wheel
  - pip install -q -r dev-requirements.txt
  - pip install -q -r requirements.txt

script:
  - >
    nosetests tests
      --nologcapture
      --verbosity=2
      --with-coverage
      --cover-package=pymanopt
    - flake8 examples pymanopt tests setup.py

after_success:
  - coveralls
  - >
    PYTHONPATH=. sphinx-build
      -b html
      -D version=dev
      -D release=dev
      docs
      website/docs

deploy:
  - provider: pypi
    user: $TWINE_USER
    password: $TWINE_PW
    on:
      repo: pymanopt/pymanopt
      tags: true
    distributions: "sdist bdist_wheel"
    skip_existing: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAGES_TOKEN
    keep_history: true
    repo: pymanopt/pymanopt.github.io
    target_branch: master
    fqdn: www.pymanopt.org
    project_name: pymanopt
    on:
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
      branch: master
      repo: pymanopt/pymanopt
    local_dir: website
